import AuthProvider from "@/components/AuthProvider";
import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Posts",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <AuthProvider>
            <html lang="en">
                <body className={"bg-gray-900"}>{children}</body>
            </html>
        </AuthProvider>
    );
}
