import AuthProvider from "@/components/AuthProvider";
import "./globals.css";
import type { Metadata } from "next";
import QueryProvider from "@/components/QueryProvider";

export const metadata: Metadata = {
    title: "Posts",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <AuthProvider>
            <QueryProvider>
                <html lang="en">
                    <body className={"bg-gray-900"}>{children}</body>
                </html>
            </QueryProvider>
        </AuthProvider>
    );
}
